import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

import { SignIn, useUser, UserButton } from "@clerk/nextjs";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime)

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const user = useUser();
  console.log("🚀 ~ file: index.tsx:13 ~ user:", user);

  const CreatePostWizard = () => {
    if (!user.isSignedIn) return null;

    return (
      <div className="flex w-full gap-4">
        {/* <img src={user.p} */}
        <h2 className="mb-4">Hi user</h2>
        <input
          placeholder="Type some emojis"
          className="grow bg-transparent "
        />
      </div>
    );
  };

  type PostWithUser = RouterOutputs["posts"]["getAll"][number];

  const PostView = (props: PostWithUser) => {
    const { post, author } = props;
    return (
      <div key={post.id} className="border-b border-slate-400 p-8">

        <span>{author.username}</span>
        <span className="font-thin">{` . ${dayjs(post.createdAt).fromNow()}`}</span>

        <p>{post.content} </p>

      </div>
    );
  };

  if (isLoading) return <div>Is loading</div>;

  if (!data) return <div>No data</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          {user.isSignedIn ? (
            <div className="mb-6">
              <UserButton afterSignOutUrl="/" />
              <CreatePostWizard />
            </div>
          ) : null}

          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

          {[...data]?.map((fullPost) => (
            <PostView key={fullPost.post.id} {...fullPost} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
