import { type NextPage } from "next";
import Head from "next/head";

import { useUser } from "@clerk/nextjs";

import { generateSSGHelper } from "~/server/helpers/ssgHelper";

import type { GetServerSideProps } from 'next';

const SinglePostPage: NextPage = () => {
  const { isLoaded: userLoaded } = useUser();


  if (!userLoaded) return <div />;


  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">

        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const ssg = generateSSGHelper();

  const id = ctx.params?.id;
  console.log("🚀 ~ file: [id].tsx:37 ~ constgetServerSideProps:GetServerSideProps= ~ id:", id)

  const posts = await ssg.posts.getAll.fetch()

  console.log("🚀 ~ file: [id].tsx:40 ~ constgetServerSideProps:GetServerSideProps= ~ posts:", posts)

  return { props: {  } };
};


export default SinglePostPage;

