import {useState} from "react"

import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

import { SignIn, useUser, UserButton, useSession } from "@clerk/nextjs";

const SinglePostPage: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();


  if (!userLoaded) return <div />;


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          
        </div>
      </main>
    </>
  );
};


export default SinglePostPage;

